### ISSUE TITLE
Setting baud rate failed

### ISSUE THREAD

**Issue by jpmeijers** [OpenBekenIOT/hid_download_py#3]
```
$ uartprogram OpenBK7231T_UA_1.0.1.bin -d /dev/ttyUSB0 -w
UartDownloader....
programm....
Set baudrate failed: |
```

When I specify the baudrate, as in `$ uartprogram OpenBK7231T_UA_1.0.1.bin -d /dev/ttyUSB0 -w -b 115200` it works. I believe my USB-UART device does not support the default baudrate.

Maybe it's worth making a note about this in the readme.

**Comment by btsimonh** [comment]
hmm.. looking at the code, I don't think it checks if the host machine's baud rate set is successfully (although this may throw an exception - i've not worked in detail with pyserial before...).  The false response comes from not getting a valid response (at the new baudrate) to the set baudrate command send to the device.
So it could be either the comms at the higher baudrate are compromised, or that the host did not change the baudrate correctly (e.g. because the adaptor could not support it.), but that this does not cause an exception, just does not change the rate...

I'll review the readme and add some additional notes....

**Comment by btsimonh** [comment]
readme updated.  Any other thoughts, just shout or PR. :).
thanks,

Simon

**Comment by zopieux** [comment]
Hey, I gave this a look, because I'm affected as well. I don't think the two hypotheses in https://github.com/OpenBekenIOT/hid_download_py/issues/3#issuecomment-1059931911 are correct, here is why.

The error happens because upon sending the `SetBaudRate` command, the serial read buffer contains **two** messages instead of just the reply to `SetBaudRate`:

 `04 0e 05 01 e0 fc 01 00 04 0e 09 01 e0 fc 0f 00 10 0e 00 14`

You can clearly see that it's actually `04 0e 05 01 e0 fc 01 00`, which AFAIU is a `WriteReg` reply (but why is it here?), followed by `04 0e 09 01 e0 fc 0f 00 10 0e 00 14`, which is the one we are looking for.

Whether this is the bootloader behaving weirdly, or uartprogram forgetting to consume one message, I do not know. The read code is the exact same code and behaves just fine, so I'm confused.

I've worked around it by just consuming this message if it's there before `SetBaudRate` reply. It worked fine and I was able to flash my device without issue (BK7231N, fyi).

**Comment by zopieux** [comment]
More specifically, this section of the README 

>So if you get a connection, but then 'Set Baudrate Failed', it could be that your connections/uart are not capable of the default 921600 baud, so try a lower one.

gives the impression the error is about incompatible rates but it's actually about the device (or the program) misbehaving. I was able to flash at the default 921600 baudrate after applying the workaround mentioned above.

**Comment by btsimonh** [comment]
@zopieux - do you have a fix which you could PR?  Python is not my first language :).

**Comment by zopieux** [comment]
Well it's not a fix but a workaround, but I can send a PR.

**Comment by Naguz** [comment]
I had what I believe to be the same problem today, with a fresh clone from the repo. I get the "Set baudrate failed"-error, but specifying the baud rate, including setting it to  921600, works without a problem. So the problem does definitely seem to be the communication regarding changing the baud rate.
